version: "3.9"
services:
  db:
    image: mongo:7.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: chaos
    ports:
      - "27137:27017"
    volumes:
      - chaos_mongodb_data:/data/db

  bot:
    build: .
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - db

networks:
  default:
    name: "chaos"

volumes:
  chaos_mongodb_data:
    driver: local